export const ERROR_CODE_VALUES = [
  "INVALID_MESSAGE",
  "UNSUPPORTED_PROTOCOL_VERSION",
  "UNAUTHORIZED",
  "PAIRING_TOKEN_INVALID",
  "SESSION_NOT_FOUND",
  "DUPLICATE_MESSAGE",
  "REMOTE_CONTROL_REVOKED",
  "INTERNAL_ERROR"
] as const;

export type ProtocolErrorCode = (typeof ERROR_CODE_VALUES)[number];